// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins(id, hospital_id)
VALUES ($1, $2)
RETURNING id, hospital_id
`

type CreateAdminParams struct {
	ID         uuid.UUID
	HospitalID uuid.NullUUID
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin, arg.ID, arg.HospitalID)
	var i Admin
	err := row.Scan(&i.ID, &i.HospitalID)
	return i, err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, hospital_id
FROM admins
WHERE id=$1
`

func (q *Queries) GetAdmin(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, id)
	var i Admin
	err := row.Scan(&i.ID, &i.HospitalID)
	return i, err
}
