// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hospitals.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createHospital = `-- name: CreateHospital :one
INSERT INTO hospitals(id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateHospitalParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateHospital(ctx context.Context, arg CreateHospitalParams) (Hospital, error) {
	row := q.db.QueryRowContext(ctx, createHospital, arg.ID, arg.Name)
	var i Hospital
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAllHospitals = `-- name: GetAllHospitals :many
SELECT id, name
FROM hospitals
`

func (q *Queries) GetAllHospitals(ctx context.Context) ([]Hospital, error) {
	rows, err := q.db.QueryContext(ctx, getAllHospitals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hospital
	for rows.Next() {
		var i Hospital
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHospital = `-- name: GetHospital :one
SELECT id, name 
FROM hospitals
WHERE id=$1
`

func (q *Queries) GetHospital(ctx context.Context, id uuid.UUID) (Hospital, error) {
	row := q.db.QueryRowContext(ctx, getHospital, id)
	var i Hospital
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
