// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ModelPrediction struct {
	ID             uuid.UUID
	PatientID      int32
	Glucose        string
	ModelVersion   string
	TimePredicted  time.Time
	GeneratedAt    time.Time
	PredictedValue string
	Accuracy       sql.NullFloat64
	OduAccuracy    sql.NullFloat64
}

type OduPrediction struct {
	ID             uuid.UUID
	PatientID      int32
	Glucose        string
	TimePredicted  time.Time
	GeneratedAt    time.Time
	PredictedValue string
	Accuracy       sql.NullFloat64
}

type Reading struct {
	ID                uuid.UUID
	PatientID         int32
	TimeOfReading     time.Time
	Glucose           string
	BasalRate         string
	Bolus             string
	Carbs             string
	ExerciseDuration  sql.NullInt32
	ExerciseIntensity sql.NullInt32
	InTheModel        sql.NullBool
}

type User struct {
	ID   int32
	Name string
}
