// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Admin struct {
	ID         uuid.UUID
	HospitalID uuid.NullUUID
}

type Hospital struct {
	ID   uuid.UUID
	Name string
}

type Model struct {
	ID      uuid.UUID
	Name    string
	Version string
}

type Prediction struct {
	ID               uuid.UUID
	ModelID          uuid.UUID
	PatientID        int32
	GlucosePredicted string
	TimePredicted    time.Time
	GeneratedAt      time.Time
}

type Reading struct {
	ID                uuid.UUID
	PatientID         int32
	TimeOfReading     time.Time
	Glucose           string
	BasalRate         string
	Bolus             string
	Carbs             string
	ExerciseDuration  sql.NullInt32
	ExerciseIntensity sql.NullInt32
	InTheModel        sql.NullBool
}

type User struct {
	ID         int32
	HospitalID uuid.NullUUID
	Name       string
}
