// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addModel = `-- name: AddModel :one
INSERT INTO models (id, name, version)
VALUES ($1, $2, $3)
RETURNING id, name, version
`

type AddModelParams struct {
	ID      uuid.UUID
	Name    string
	Version string
}

func (q *Queries) AddModel(ctx context.Context, arg AddModelParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, addModel, arg.ID, arg.Name, arg.Version)
	var i Model
	err := row.Scan(&i.ID, &i.Name, &i.Version)
	return i, err
}

const getAllModels = `-- name: GetAllModels :many
SELECT id, name, version FROM models
`

func (q *Queries) GetAllModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, getAllModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(&i.ID, &i.Name, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
