// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readings.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addReading = `-- name: AddReading :one
INSERT INTO readings(id, patient_id, time_of_reading, glucose, basal_rate, bolus, carbs, exercise_duration, exercise_intensity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, patient_id, time_of_reading, glucose, basal_rate, bolus, carbs, exercise_duration, exercise_intensity, in_the_model
`

type AddReadingParams struct {
	ID                uuid.UUID
	PatientID         uuid.UUID
	TimeOfReading     time.Time
	Glucose           string
	BasalRate         string
	Bolus             string
	Carbs             string
	ExerciseDuration  sql.NullInt32
	ExerciseIntensity sql.NullInt32
}

func (q *Queries) AddReading(ctx context.Context, arg AddReadingParams) (Reading, error) {
	row := q.db.QueryRowContext(ctx, addReading,
		arg.ID,
		arg.PatientID,
		arg.TimeOfReading,
		arg.Glucose,
		arg.BasalRate,
		arg.Bolus,
		arg.Carbs,
		arg.ExerciseDuration,
		arg.ExerciseIntensity,
	)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.TimeOfReading,
		&i.Glucose,
		&i.BasalRate,
		&i.Bolus,
		&i.Carbs,
		&i.ExerciseDuration,
		&i.ExerciseIntensity,
		&i.InTheModel,
	)
	return i, err
}

const getReadings = `-- name: GetReadings :many
SELECT id, patient_id, time_of_reading, glucose, basal_rate, bolus, carbs, exercise_duration, exercise_intensity, in_the_model FROM readings
WHERE patient_id=$1
`

func (q *Queries) GetReadings(ctx context.Context, patientID uuid.UUID) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, getReadings, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.TimeOfReading,
			&i.Glucose,
			&i.BasalRate,
			&i.Bolus,
			&i.Carbs,
			&i.ExerciseDuration,
			&i.ExerciseIntensity,
			&i.InTheModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnseenReadings = `-- name: GetUnseenReadings :many
SELECT id, patient_id, time_of_reading, glucose, basal_rate, bolus, carbs, exercise_duration, exercise_intensity, in_the_model FROM readings
WHERE patient_id=$1
AND in_the_model=false
`

func (q *Queries) GetUnseenReadings(ctx context.Context, patientID uuid.UUID) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, getUnseenReadings, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.TimeOfReading,
			&i.Glucose,
			&i.BasalRate,
			&i.Bolus,
			&i.Carbs,
			&i.ExerciseDuration,
			&i.ExerciseIntensity,
			&i.InTheModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendReadingToModel = `-- name: SendReadingToModel :exec
UPDATE readings
SET in_the_model=true
WHERE id=$1
`

func (q *Queries) SendReadingToModel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, sendReadingToModel, id)
	return err
}
