// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package database

import (
	"context"
)

const getRecommendation = `-- name: GetRecommendation :one
SELECT id, patient_id, is_safe, action, message, created_at 
FROM recommendations
WHERE patient_id=$1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetRecommendation(ctx context.Context, patientID int32) (Recommendation, error) {
	row := q.db.QueryRowContext(ctx, getRecommendation, patientID)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.IsSafe,
		&i.Action,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
