// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name)
SELECT 
    CASE WHEN $1::INT = 0 THEN nextval(pg_get_serial_sequence('users', 'id')) ELSE $1::INT END, 
    $2
RETURNING id, name
`

type CreateUserParams struct {
	Column1 int32
	Name    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Column1, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
